### ISSUE TITLE
Error Cannot GET /

### ISSUE THREAD

**Issue by junioralive** [dhvitOP/AnimeEZ-api#1]
when i open Api running on port 6969. Add http://localhost:6969 to the website config.
it says Cannot GET /

**Comment by dhvitish** [comment]
It is an api so there are routes. I guess ill add a sitemap or list of routes and there works.

**Comment by dhvitish** [comment]
Please use [AnimeEZ](https://github.com/dhvitOP/AnimeEZ) for website.

**Comment by junioralive** [comment]
thank you

**Comment by junioralive** [comment]
but still it says Cannot GET /naruto

**Comment by dhvitish** [comment]
Ig the problem is solved now.

**Comment by KshitijKalambe** [comment]
i don't get it all routes are properly defined?
